### ISSUE TITLE
Should Recursively Apply Roles to Includes

### ISSUE THREAD

**Issue by lauzierj** [mickhansen/ssacl-attribute-roles#1]
In the following example, values.company.price should return a truthy value but it does not. I have a pull request enroute.

``` javascript
var Company = sequelize.define('company', {
  price: {
    type: Sequelize.FLOAT,
    roles: {
      admin: true
    }
  },
  name: Sequelize.STRING
});

var user = User.build({
  id: 12,
  companyId: 14,
  email: Math.random().toString(),
  password: Math.random().toString(),
  company: {
    id: 14,
    price: Math.random(),
    name: Math.random().toString()
  }
}, {
  role: { system: true }, // I'm not sure what this does
  include: [Company]
});

var values = user.get({role: 'admin'});

expect(values.company.price).to.be.ok();
```

**Comment by lauzierj** [comment]
I had a typo in my example above. I was playing around with the part I didn't understand (re: role is system for the build options).

I will leave it the same as it was, but can you clarify what it does?

**Comment by mickhansen** [comment]
`role` on `build` sets the role for `set`, i.e. it's only allowed to set the values that role can set.

**Comment by djvs** [comment]
Sorry to resurrect, but what is the actual way to address this?  I migrated my model to use ssacl on your recommendation @mickhansen  and now notice it's including this attribute:

    password: {
      type: DataTypes.STRING,
      roles: {admin: true}
    },

In an include from another model.

**Comment by djvs** [comment]
Sorry, ignore previous
