### ISSUE TITLE
Can be used in a `findAll` and `findOne`?

### ISSUE THREAD

**Issue by diosney** [mickhansen/ssacl-attribute-roles#8]
I tried something like:

``` js
models
    .Person
    .findAll({
       role: 'aRole'
    })
```

and configured the attribute as:

``` js
     aModelAttribute  : {
        type        : global.app.orm.Sequelize.BOOLEAN,
        defaultValue: false,
        roles       : {
          aRole: {
            get: true
          }
        }
      }
```

but didn't show the attribute in the results.

**Comment by mickhansen** [comment]
No, it currently only works for `get` and `set` (and by proxy `update`)

**Comment by diosney** [comment]
@mickhansen Good to confirm. There is any recommended way to accomplish that different from iterating over the results and triggering `.get()`?

Thanks.

**Comment by mickhansen** [comment]
Should happen automatically in most cases. `JSON.stringify` which most http libraries use triggers `toJSON` which triggers `.get()`

**Comment by diosney** [comment]
But how do I pass the role to the inner `.get()` from the `stringify` call, or something?

Right now it is not displaying the attribute, and what I need is to show it for several records at a time.

Thanks, and sorry if this is too simple or custom :(

**Comment by mickhansen** [comment]
Ah right, my mind blanked on that for a second. You will need to have a map on the array before sending a response.

`this.body = results.map(result => result.get({role: 'role'}))`

**Comment by diosney** [comment]
@mickhansen Ok thanks!
